### ISSUE TITLE
Using $ref for a parameter crashes oapi-codegen

### ISSUE THREAD

**Issue by Jleagle** [deepmap/oapi-codegen#139]
Running oapi-codegen on yaml that has $ref parameter causes a crash

    parameters:
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/limit'
      - name: search
        in: query

But, if you fill in the parameter and $ref the parameter schema it works, tested in [internal/test/parameters/parameters.yaml](https://github.com/deepmap/oapi-codegen/blob/master/internal/test/parameters/parameters.yaml).

Thanks.

**Comment by deepmap-marcinr** [comment]
Ooh, nasty. Thanks for the report.

**Comment by deepmap-marcinr** [comment]
So, I can't reproduce this. I've edited the  internal/test/parameters/parameters.yaml to use $ref for parameters, and it doesn't crash.

Could you provide a stack trace, and the exact yaml file you're using?

**Comment by Jleagle** [comment]
Hi, I am generating the json using `getkin/kin-openapi/openapi3`

The error i get when i use $ref is:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13d6509]

goroutine 1 [running]:
github.com/deepmap/oapi-codegen/pkg/codegen.DescribeParameters(0xc00019c780, 0x1, 0x4, 0xc0001719e0, 0x1, 0x1, 0xd, 0x0, 0x0, 0x0, ...)
        /Users/james/go/pkg/mod/github.com/deepmap/oapi-codegen@v1.3.4/pkg/codegen/operations.go:149 +0xc9
github.com/deepmap/oapi-codegen/pkg/codegen.OperationDefinitions(0xc0000d26c0, 0xc0000ed180, 0x0, 0x0, 0x0, 0x0)
        /Users/james/go/pkg/mod/github.com/deepmap/oapi-codegen@v1.3.4/pkg/codegen/operations.go:402 +0x3fd
github.com/deepmap/oapi-codegen/pkg/codegen.Generate(0xc0000d26c0, 0x7ffeefbfda06, 0x9, 0x101000001, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/james/go/pkg/mod/github.com/deepmap/oapi-codegen@v1.3.4/pkg/codegen/codegen.go:102 +0x10b
main.main()
        /Users/james/go/pkg/mod/github.com/deepmap/oapi-codegen@v1.3.4/cmd/oapi-codegen/oapi-codegen.go:98 +0x66d

```

With $ref: https://textuploader.com/1620t
Without $ref: https://textuploader.com/1620r

The only difference between the two is close to the bottom where the $ref is added/removed.

Thanks.

**Comment by deepmap-marcinr** [comment]
Oh, I see. This file contains JSON, but if I paste it into a file with a .yaml suffix, it works :) It's a bug with file type detection.

**Comment by Jleagle** [comment]
My original example was just in YAML as I thought most people use it over JSON.

I can successfully run oapi-codegen on my json with a regular parameter, but as soon as I switch the parameter to a $ref of the same parameter (the two linked files) it crashes and gives me the stack trace above.

The command i am running is:
```bash
oapi-codegen \
  -o generated.go \
  -generate types,chi-server,spec \
  -package generated \
  openapi.json
```

Thanks.

**Comment by deepmap-marcinr** [comment]
It was a bug. I fixed it in HEAD. I'll push a release with a few more fixes in a few days.

**Comment by deepmap-marcinr** [comment]
I was accidentally saving your JSON data into a .yaml suffix file, and it worked great, which is why I didn't see the problem :)

**Comment by Jleagle** [comment]
As far as I can tell, this is still an issue in v1.3.6. Thanks.

**Comment by deepmap-marcinr** [comment]
I don't understand why we are seeing different results. I just downloaded your two textuploader files, and both successfully generate the boilerplate, no crashes, no errors, both files compile fine.

I tried the 1.3.6 version, and HEAD - both work.

Are you sure you're running what you think you're running? I need to add a --version flag, I think.

**Comment by Jleagle** [comment]
You were right, I updated oapi-codgen in my project but it didn't update the binary in the go bin folder and was still using v1.3.4. Thanks.
